### ISSUE TITLE
Práctica 8-Roadmap

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-entrevista_equipo-irving#3]
[Practica Roadmap.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-entrevista_equipo-irving/files/13190932/Practica.Roadmap.pdf)

**Comment by bg55-a** [comment]
Calif: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
